config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :forms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    forms_path
  end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create ]

  def index
      @forms = Form.all
  end

  def show
    @form = Form.find(params[:id])
  end

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @form = Form.find(params[:id])
  end

  def update
    @form = Form.find(params[:id])
    if @form.update(form_params)
      if current_user.admin
        redirect_to form_path(params[:id])
      else
        redirect_to root_path
      end
    else
      render :edit
    end
  end

  def destroy
    @form = Form.find(params[:id])
    @form.destroy!
    redirect_to forms_path
  end

  private

  def form_params
    params.require(:form).permit(
        :name,
        :phone,
        :prefecture,
        :address,
        :driver,
        :licences,
        :passport,
        :my_number,
        :observations,
        :previous_job,
        :job_kind
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forms/_form.html.erb
  <%= simple_form_for (form) do |f| %>
  <div class="forms">
    <%= f.input :name, label: "Nome Completo:" %>
    <%= f.input :phone, label: "Telefone de Contato:" %>
    <%= f.input :email, label: "Email:" %>
    <%= f.input :prefecture, label: "Prefeitura:" %>
    <%= f.input :address, label: "Endereço:" %>
    <%= f.input :driver, label: "Carteira de Motorista:" %>
    <%= f.input :licences, label: "Outras Licenças ou Carteiras:" %>
    <%= f.input :passport, label: "Passaporte:" %>
    <%= f.input :my_number, label: "My Number(se houver):" %>
    <%= f.input :previous_job, label: "Experiência anterior:" %>
    <%= f.input :job_kind, label: "Que tipo de trabalho você está procurando:" %>
    <%= f.input :observations, label: "Outras observações(apto, mudança, etc...):" %>
    <div class="text-center">
      <% if @form.persisted? %>
      <%= f.submit "EDITAR", class:"btn btn-ghost" %>
      <% else %>
      <button type="button" class="btn btn-ghost add-btn" data-toggle="modal" data-target="#exampleModal">
        CADASTRAR
      </button>
      <% end %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Termo de Conconrdancia</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Concordo em disponibilizar meus dados para futuro
            contato, no que diz respeito a oportunidade de trabalho.
            Me reponsabilizo pela veracidade das informações fornecidas.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-ghost" data-dismiss="modal">FECHAR</button>
            <%= f.submit "CADASTRAR", class:"btn btn-ghost" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/forms/edit.html.erb
<h1 class="text-center mt-3">EDIÇÃO DE CADASTRO</h1>
<div class="text-center">
  <%= link_to "VOLTAR", forms_path, class: "btn btn-ghost" %>
</div>
<%= render 'forms/form', form: @form %>

app/views/forms/index.html.erb
<% @forms.each do |form| %>
<div class="card mt-3">
  <div class="card-body d-flex justify-content-between">
    <p><%= form.name %></p>
    <p><%= form.phone %></p>
  </div>
  <div class="card-body d-flex justify-content-between">
    <%= link_to 'Visualizar', form_path(form), class: 'btn btn-ghost btn-sm' %>
    <%= link_to 'Editar', edit_form_path(form), class: 'btn btn-ghost btn-sm' %>
    <%= link_to 'Apagar', form_path(form), class: 'btn btn-ghost btn-sm', method: :delete, data: { confirm: 'Gostaria de apagar esse cadastro?' } %>
  </div>
</div>
<% end %>

app/views/forms/new.html.erb
<h1 class="text-center mt-3">SEU CADASTRO</h1>
<div class="text-center">
  <%= link_to "VOLTAR", root_path, class: "btn btn-ghost" %>
</div>
<%= render 'forms/form', form: @form %>

app/views/forms/show.html.erb
<h1 class="text-center mt-3">CADASTRO</h1>
<div class="text-center">
  <%= link_to "VOLTAR", forms_path, class: "btn btn-ghost" %>
</div>
<div class="card mt-3">
  <h3 class="text-center m-3"><%= @form.name %></h3>
  <label>Telefone:</label>
  <p class="card-body"><%= @form.phone %></p>
  <label>Endereço:</label>
  <p class="card-body"><%= @form.prefecture %></p>
  <p class="card-body"><%= @form.address %></p>
  <label>Email:</label>
  <p class="card-body"><%= @form.email %></p>
  <label>Habilitação:</label>
  <p class="card-body"><%= @form.driver ? "Possui Carteira de Motorista" : "Não possui Carteira de Motorista" %></p>
  <label>Outras habilitações:</label>
  <p class="card-body"><%= @form.licences %></p>
  <label>Passaporte:</label>
  <p class="card-body"><%= @form.passport %></p>
  <label>My Number:</label>
  <p class="card-body"><%= @form.my_number %></p>
  <label>Experiência anterior:</label>
  <p class="card-body"><%= @form.previous_job %></p>
  <label>Que tipo de trabalho você procura?:</label>
  <p class="card-body"><%= @form.job_kind %></p>
  <label>Observações:</label>
  <p class="card-body"><%= @form.observations %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forms</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class="d-flex justify-content-center align-items-center base">
  <%= link_to 'CADASTRO', new_form_path, class:"btn btn-ghost" %>
</div>
<div>
  <p>** Tia pode usar esse email e senha. **</p>
  <p>Email = inomata@email.com</p>
  <p>Senha = Inomata</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="far fa-clipboard fa-2x"></i>
    <% end %>

  <div>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
            <%= link_to "CADASTROS", forms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "SAIR", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ENTRAR", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>